# nixpacks.toml

[phases.install]
cmds = [
    "mkdir -p /app/storage/framework/views /app/storage/framework/cache /app/p/storage/framework/sessions",
    "chmod -R 775 /app/storage"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run prod"
]

[start]
cmd = "/usr/bin/env -S node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx/nginx.conf && php-fpm -y /assets/php-fpm.conf -F & nginx -c /etc/nginx/nginx.conf"



