# nixpacks.toml

[variables]
NIXPACKS_PHP_FALLBACK_PATH = ""
IS_LARAVEL = ""

[phases.install]
cmds = [
    "mkdir -p /app/storage/framework/views /app/storage/framework/cache /app/p/storage/framework/sessions",
    "chmod -R 775 /app/storage"
]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/ /var/log/nginx",
    "touch /var/log/nginx/error.log /var/log/nginx/access.log",
    "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "chmod +x /assets/start.sh"
]

[start]
cmd = "/usr/bin/env -S node /assets/scripts/prestart.mjs /assets/nginx.template.conf /tmp/nginx.conf && nginx -c /tmp/nginx.conf & php-fpm -y /assets/php-fpm.conf -F"



