# nixpacks.toml

[phases.install]
cmds = [
    "mkdir -p /app/storage/framework/views /app/storage/framework/cache /app/p/storage/framework/sessions",
    "chmod -R 775 /app/storage"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "echo '--- DEBUG: Contents of package.json ---'",
    "cat /app/public_html/package.json",
    "echo '--- DEBUG: Contents of postcss.config.js ---'",
    "cat /app/public_html/postcss.config.js",
    "echo '--- END DEBUG ---'",
    "npm run prod"
]

[start]
cmd = "php-fpm -y /assets/php-fpm.conf -F & nginx -c /assets/nginx.conf"



