# nixpacks.toml

[phases.install]
cmds = [
    "mkdir -p /app/storage/framework/views /app/storage/framework/cache /app/p/storage/framework/sessions",
    "chmod -R 775 /app/storage"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run prod"
]

[start]
cmd = "php-fpm -y /assets/php-fpm.conf -F & nginx -c /assets/nginx.conf"



